package aplicacion.hibernate.mapeos;
// Generated Jun 5, 2019 12:08:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private int codProducto;
     private Categorias categorias;
     private String descripcion;
     private Double precio;
     private Integer stock;
     private Set detalles = new HashSet(0);

    public Productos() {
    }

	
    public Productos(int codProducto, Categorias categorias) {
        this.codProducto = codProducto;
        this.categorias = categorias;
    }
    public Productos(int codProducto, Categorias categorias, String descripcion, Double precio, Integer stock, Set detalles) {
       this.codProducto = codProducto;
       this.categorias = categorias;
       this.descripcion = descripcion;
       this.precio = precio;
       this.stock = stock;
       this.detalles = detalles;
    }
   
    public int getCodProducto() {
        return this.codProducto;
    }
    
    public void setCodProducto(int codProducto) {
        this.codProducto = codProducto;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }




}


