package aplicacion.modelo.dominio;
// Generated Jun 4, 2019 12:47:47 PM by Hibernate Tools 4.3.1



/**
 * Autor generated by hbm2java
 */
public class Autor  implements java.io.Serializable {


     private int dni;
     private String nombre;
     private String apellido;

    public Autor() {
    }

	
    public Autor(int dni) {
        this.dni = dni;
    }
    public Autor(int dni, String nombre, String apellido) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellido = apellido;
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }




}


